package tests

import microwave.model.Microwave
import org.scalatest.FunSuite

class TestCookTime extends FunSuite {

  test("Enter Time Cook") {
    val microwave: Microwave = new Microwave()
    microwave.numberPressed(3)
    microwave.numberPressed(0)
    assert(microwave.currentInstructions().cookTime == 0)
    microwave.startPressed()
    assert(microwave.currentInstructions().cookTime == 30)
    microwave.clearPressed()
    microwave.numberPressed(1)
    microwave.numberPressed(2)
    microwave.numberPressed(4)
    microwave.cookTimePressed()
    microwave.numberPressed(5)
    microwave.numberPressed(6)
    microwave.numberPressed(7)
    microwave.numberPressed(8)
    microwave.startPressed()
    assert(microwave.currentInstructions().cookTime==5678)

    val MicrowaveSuck:Microwave=new Microwave()
    MicrowaveSuck.thirtySecondsPressed()
    assert(MicrowaveSuck.currentInstructions().cookTime==30)
    MicrowaveSuck.clearPressed()
    MicrowaveSuck.numberPressed(9)
    MicrowaveSuck.numberPressed(1)
    MicrowaveSuck.numberPressed(2)
    MicrowaveSuck.numberPressed(4)
    MicrowaveSuck.startPressed()
    assert(MicrowaveSuck.currentInstructions().cookTime==9124)
  }
  test("will it work"){
    val microwave2: Microwave = new Microwave()
    microwave2.thirtySecondsPressed()
    assert(microwave2.currentInstructions().cookTime==30)
  }
  test("plus_30_only_start"){
    val microwave3: Microwave = new Microwave()
    microwave3.thirtySecondsPressed()
    assert(microwave3.currentInstructions().cookTime == 30)
    assert(microwave3.currentInstructions().powerLevel==100)
  }

  //  val microwave: Microwave = new Microwave()
//  // Example test case
//  test("example test one"){
//    val microwave2: Microwave = new Microwave()
//    microwave2.thirtySecondsPressed()
//    assert(microwave2.currentInstructions().cookTime == 30)
////    assert(microwave.currentInstructions().cookTime == 0)
////    microwave.numberPressed(1)
////    microwave.numberPressed(2)
////    microwave.numberPressed(3)
////    microwave.numberPressed(4)
////    microwave.numberPressed(5)
////    microwave.numberPressed(6)
////    microwave.numberPressed(7)
////    microwave.numberPressed(8)
////    microwave.numberPressed(9)
////    microwave.numberPressed(0)
////    assert(microwave.currentInstructions().cookTime == 0)
//  }
//  test("test case two"){
//    assert(microwave.currentInstructions().cookTime == 0)
//            microwave.numberPressed(1)
//    assert(microwave.currentInstructions().cookTime == 0)
//            microwave.numberPressed(2)
//            microwave.numberPressed(3)
//            microwave.numberPressed(4)
//            microwave.numberPressed(5)
//            microwave.numberPressed(6)
//            microwave.numberPressed(7)
//            microwave.numberPressed(8)
//            microwave.numberPressed(9)
//            microwave.numberPressed(0)
//    microwave.startPressed()
//    microwave.thirtySecondsPressed()
//    microwave.thirtySecondsPressed()
//    //microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1234567950)
//
//
////    assert(microwave.currentInstructions().cookTime == 30)
//  }

 // test("Enter Time Cook / 30 sec of close and open door") {

    //Example test
    //example test one
//        assert(microwave.currentInstructions().cookTime == 0)
//        microwave.numberPressed(1)
//        microwave.numberPressed(2)
//        microwave.numberPressed(3)
//        microwave.numberPressed(4)
//        microwave.numberPressed(5)
//        microwave.numberPressed(6)
//        microwave.numberPressed(7)
//        microwave.numberPressed(8)
//        microwave.numberPressed(9)
//        microwave.numberPressed(0)
//        assert(microwave.currentInstructions().cookTime == 0)
//        microwave.clearPressed()
//        microwave.startPressed()
//        assert(microwave.currentInstructions().cookTime == 0)
//        microwave.clearPressed()
//        assert(microwave.currentInstructions().cookTime == 0)
    //example test two
//        assert(microwave.currentInstructions().cookTime == 0)
////        microwave.numberPressed(1)
////        microwave.numberPressed(2)
//        microwave.numberPressed(3)
////        microwave.numberPressed(4)
////        microwave.numberPressed(5)
////        microwave.numberPressed(6)
////        microwave.numberPressed(7)
////        microwave.numberPressed(8)
////        microwave.numberPressed(9)
//        microwave.numberPressed(0)
//        microwave.startPressed()
//        //assert(microwave.currentInstructions().cookTime == 1234567890)
//        assert(microwave.currentInstructions().cookTime == 30)
//        microwave.clearPressed()
    //example test three
    //testing 30 close
//        assert(microwave.currentInstructions().cookTime == 0)
//        microwave.thirtySecondsPressed()
//        assert(microwave.currentInstructions().cookTime==30)
//        microwave.clearPressed()
////        assert(microwave.currentInstructions().cookTime == 0)
////        microwave.numberPressed(1)
////        microwave.numberPressed(2)
////        microwave.thirtySecondsPressed()
////        assert(microwave.currentInstructions().cookTime==42)
////        microwave.clearPressed()
////        assert(microwave.currentInstructions().cookTime == 0)
////        microwave.numberPressed(1)
////        microwave.thirtySecondsPressed()
////        assert(microwave.currentInstructions().cookTime==31)
////        microwave.thirtySecondsPressed()
////        assert(microwave.currentInstructions().cookTime==61)
//        microwave.clearPressed()








    //one test to all without clear
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(3)
//    microwave.numberPressed(4)
//    microwave.numberPressed(5)
//    microwave.numberPressed(6)
//    microwave.numberPressed(7)
//    microwave.numberPressed(8)
//    microwave.numberPressed(9)
//    microwave.numberPressed(0)

//    assert(microwave.currentInstructions().cookTime == 0)
//    //testing all the number close

//

//

//
//
//    //testing all the number open
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(3)
//    microwave.numberPressed(4)
//    microwave.numberPressed(5)
//    microwave.numberPressed(6)
//    microwave.numberPressed(7)
//    microwave.numberPressed(8)
//    microwave.numberPressed(9)
//    microwave.numberPressed(0)
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1234567890)
//    microwave.clearPressed()
//
//    //testing 30 open
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.openDoor()
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime==30)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime==42)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime==31)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime==61)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.openDoor()
//    microwave.thirtySecondsPressed()
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime==60)
//    microwave.closeDoor()
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //+ 30 while running
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(3)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 153)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 183)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 213)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //add number after running open door
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 11)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.closeDoor()
//    microwave.numberPressed(1)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 111)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //add 30 after running open door
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 30)
//    microwave.openDoor()
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 60)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 30)
//    microwave.openDoor()
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 90)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //add 30+1 after running open door
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 31)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 341)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 31)
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 3441)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //all number  wont work while running
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1)
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(3)
//    microwave.numberPressed(4)
//    microwave.numberPressed(5)
//    microwave.numberPressed(6)
//    microwave.numberPressed(7)
//    microwave.numberPressed(8)
//    microwave.numberPressed(9)
//    microwave.numberPressed(0)
//    microwave.clearPressed()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1)
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(3)
//    microwave.numberPressed(4)
//    microwave.numberPressed(5)
//    microwave.numberPressed(6)
//    microwave.numberPressed(7)
//    microwave.numberPressed(8)
//    microwave.numberPressed(9)
//    microwave.numberPressed(0)
//    microwave.openDoor()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //the button 0 is work
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(0)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(0)
//    microwave.startPressed()
//    microwave.doorOpen()
//    microwave.numberPressed(0)
//    microwave.closeDoor()
//    microwave.startPressed()
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //popcorn is working
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.popcornPressed()
//    assert(microwave.currentInstructions().cookTime == 140)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.popcornPressed()
//    microwave.popcornPressed()
//    assert(microwave.currentInstructions().cookTime == 140)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.popcornPressed()
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 170)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 200)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.popcornPressed()
//    microwave.openDoor()
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 170)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.popcornPressed()
//    microwave.openDoor()
//    microwave.numberPressed(1)
//    microwave.closeDoor()
//    microwave.numberPressed(1)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 14011)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.popcornPressed()
//    microwave.openDoor()
//    microwave.thirtySecondsPressed()
//    microwave.closeDoor()
//    microwave.popcornPressed()
//    assert(microwave.currentInstructions().cookTime == 140)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    //cook time button
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.cookTimePressed()
//    microwave.numberPressed(2)
//    microwave.numberPressed(0)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 20)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.cookTimePressed()
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(3)
//    microwave.numberPressed(4)
//    microwave.numberPressed(5)
//    microwave.numberPressed(6)
//    microwave.numberPressed(7)
//    microwave.numberPressed(8)
//    microwave.numberPressed(9)
//    microwave.numberPressed(0)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime == 1234567890)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.cookTimePressed()
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 30)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.numberPressed(1)
//    microwave.cookTimePressed()
//    microwave.numberPressed(1)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime == 31)
//    microwave.clearPressed()
//    assert(microwave.currentInstructions().cookTime == 0)






  //}
//  test("Enter Time Cook") {
//    val microwave: Microwave = new Microwave()
//
//    microwave.numberPressed(3)
//    microwave.numberPressed(0)
//
//    assert(microwave.currentInstructions().cookTime == 0)
//
//    microwave.startPressed()
//
//    assert(microwave.currentInstructions().cookTime == 30)
//    microwave.clearPressed()
//    microwave.numberPressed(1)
//    microwave.numberPressed(2)
//    microwave.numberPressed(4)
//    microwave.cookTimePressed()
//    microwave.numberPressed(5)
//    microwave.numberPressed(6)
//    microwave.numberPressed(7)
//    microwave.numberPressed(8)
//    microwave.startPressed()
//    assert(microwave.currentInstructions().cookTime==5678)
//    microwave.thirtySecondsPressed()
//    assert(microwave.currentInstructions().cookTime==5708)
//
//
//    val a:Microwave=new Microwave()
//    a.thirtySecondsPressed()
//    assert(a.currentInstructions().cookTime==30)
//    a.clearPressed()
//    a.numberPressed(9)
//    a.numberPressed(1)
//    a.numberPressed(2)
//    a.numberPressed(4)
//    a.startPressed()
//    assert(a.currentInstructions().cookTime==9124)
//
//
//
//  }

}
